/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cenafilosofos;

import javax.swing.JLabel;

/**
 *
 * @author Roger
 */
public class FrmCenaFilosofos extends javax.swing.JFrame {
    public static JLabel[] lblsFilosofos = new javax.swing.JLabel[5];
    public static JLabel[] lblsPalillos = new javax.swing.JLabel[5];
    
    public int[][] posicionLblFilosofos = {{240, 90, 90, 20}, {30, 230, 90, 20}, {110, 470, 90, 20}, {360, 470, 90, 20}, {440, 240, 90, 20}};
    public int[][] posicionLblPalillos = {{130, 130, 110, 90}, {80, 300, 110, 90}, {220, 410, 110, 90}, {360, 300, 110, 90}, {320, 130, 110, 90}};

    /**
     * Creates new form FrmCenaFilosofos
     */
    public FrmCenaFilosofos() {
        initComponents();
        crearLblFilosofos();
        crearLblPalillos();
        crearMesaFilosofos();
    }
    
    private void crearMesaFilosofos() {
        javax.swing.JLabel lblCena = new javax.swing.JLabel();
        lblCena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cena.jpg"))); // NOI18N
        getContentPane().add(lblCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
    }
    
    
    private void crearLblFilosofos() {
        for(int i=0; i < lblsFilosofos.length; i ++ ) {
            lblsFilosofos[i] = new javax.swing.JLabel();
            lblsFilosofos[i].setFont(new java.awt.Font("Tahoma", 1, 12));            
            lblsFilosofos[i].setForeground(new java.awt.Color(255, 255, 255));
            lblsFilosofos[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblsFilosofos[i].setText(".....");
            lblsFilosofos[i].setVisible(true);
            int val1 = posicionLblFilosofos[i][0];
            int val2 = posicionLblFilosofos[i][1];
            int val3 = posicionLblFilosofos[i][2];
            int val4 = posicionLblFilosofos[i][3];
            getContentPane().add(lblsFilosofos[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(val1, val2, val3, val4));
        }
        
    }
    
    private void crearLblPalillos() {
        for (int i=0; i < lblsPalillos.length; i++) {
            lblsPalillos[i] = new javax.swing.JLabel();
            lblsPalillos[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png")));
            lblsPalillos[i].setText("");
            lblsPalillos[i].setVisible(false);
            int val1 = posicionLblPalillos[i][0];
            int val2 = posicionLblPalillos[i][1];
            int val3 = posicionLblPalillos[i][2];
            int val4 = posicionLblPalillos[i][3];
            getContentPane().add(lblsPalillos[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(val1, val2, val3, val4));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cena de los filosofos");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CENA DE LOS FILOSOFOS");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, -1));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 120, 30));

        btnIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        CenaFilosofos.empezarCena();
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCenaFilosofos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCenaFilosofos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCenaFilosofos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCenaFilosofos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCenaFilosofos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
